services:
    - type: web
      name: imamzain-api
      runtime: node
      buildCommand: npm install
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 10000
      healthCheckPath: /
